### ISSUE TITLE
Bookshelf Fails getAllBookTitles Test and getNumberOfBooks Test

### ISSUE THREAD

**Issue by corysabol** [sible777/Concordanator#13]
``` java
array lengths differed, expected.length=20 actual.length=0
junit.framework.AssertionFailedError
    at ClassLibrary.BookshelfTest.testGetAllBookTitles(BookshelfTest.java:113)

expected:<20> but was:<0>
junit.framework.AssertionFailedError
    at ClassLibrary.BookshelfTest.testGetNumberOfBooks(BookshelfTest.java:72)
```

I will dig into this some more tomorrow when it isn't 3am. I know that it was working on your machine, however it does not work on mine. It could be the linux environment, or my test could be bad. 

Anyhow we need to address this.

**Comment by corysabol** [comment]
Still need to retest this.

**Comment by corysabol** [comment]
Closing as resolved.
