### ISSUE TITLE
Concordance loading NULL ref

### ISSUE THREAD

**Issue by corysabol** [sible777/Concordanator#27]
#### branch: CmdRepl

``` java
Peter Pan by J. M. Barrie > numoccur pan
Exception in thread "main" java.lang.NullPointerException
    at ClassLibrary.CmdRepl.numOccurences(CmdRepl.java:450)
    at ClassLibrary.CmdRepl.evalCmd(CmdRepl.java:228)
    at ClassLibrary.CmdRepl.startRepl(CmdRepl.java:127)
    at Concordanator.main(Concordanator.java:23)
```

The application crashes due to a NullPointerException when trying to query a "loaded" con.

I debugged this to learn that for some reason the con is never being deserialized properly and then `this.concord` in `CmdRepl` is being set to a null reference causing this to happen. So, the issue I think lies somewhere in the serialization/deserialization process.

Could @Metalaxe1 or @askewseth try to reproduce this and comment your findings here?

I will look into it more tomorrow. This same error also arises on any query command.

**Comment by corysabol** [comment]
I don't remember how we resolved this. But it's fixed, so I'm closing it.
